name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '13', '14' ]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2
      env:
        cache-name: cache-m2-repository
      with:
        path: ~/.m2/repository
        key: ${{ hashFiles('pom.xml') }}
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: print Java version
      run: java -version
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Run test projects
      run: make clean test
